apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-np
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ecommerce-app.name" . }}
  policyTypes: ["Ingress","Egress"]
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
