apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ecommerce-app.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "ecommerce-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
