apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: "*"
    helm:
      values: |
        clusterName: <EKS_CLUSTER_NAME>        # <-- set
        region: <AWS_REGION>                   # <-- set
        vpcId: <VPC_ID>                        # <-- set
        serviceAccount:
          # Reuse the SA created by Terraform IRSA module:
          create: false
          name: aws-load-balancer-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
